unbind C-b
# Main prefix
set -g prefix C-a
bind C-a send-prefix

# Optional extra prefix during transition
set -g prefix2 C-b
bind C-b send-prefix -2

##### Reload
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

##### General
set -g mouse on
set -g history-limit 50000
set -g renumber-windows on
set -sg escape-time 10
set -g display-time 2000
set -sg repeat-time 800

##### Better numbering
set -g base-index 1
setw -g pane-base-index 1


##### Vi motions and easier Copy/paste mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel


##### Status bar - clean and subtle
set -g status-position bottom
set -g status-justify left
set -g status-style "fg=colour252,bg=colour236"
set -g status-left-length 40
set -g status-right-length 80
#set -g status-interval 5

#set -g status-left "#[fg=colour81,bold]#S #[fg=colour244]| #[fg=colour250]#(whoami)@#H "
set -g status-left "#[fg=colour81,bold]#S #[fg=colour244]| #[fg=colour250]#H "
#set -g status-right "#[fg=colour244]%Y-%m-%d #[fg=colour250]%H:%M "
#set -g status-right "#[fg=colour250]disk #(df -h / | awk 'NR==2 {print \$4}') #[fg=colour244]| #[fg=colour250]load #(cut -d' ' -f1-3 /proc/loadavg) "
set -g status-right ""


##### Window tabs
set -g window-status-format " #[fg=colour250]#I:#W "
set -g window-status-current-format " #[fg=colour232,bg=colour81,bold]#I:#W "
#set -g window-status-format " #[fg=colour250]#W "
#set -g window-status-current-format " #[fg=colour232,bg=colour81,bold]#W "

set -g window-status-style "fg=colour250,bg=colour236"
set -g window-status-current-style "fg=colour232,bg=colour81"
set -g window-status-separator ""

##### Activity / bells
setw -g monitor-activity on
set -g visual-activity off
setw -g monitor-bell off
set -g visual-bell off
set -g window-status-activity-style "fg=colour231,bg=colour166,bold"

##### Pane borders
set -g pane-border-style "fg=colour239"
set -g pane-active-border-style "fg=colour81"

##### Splits in current path
bind | split-window -h -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

##### Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

##### Pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

##### Previous window
bind Tab last-window

##### Window chooser
bind w choose-tree -Zw

##### 3 equal horizontal panes (3 columns)
bind 3 split-window -h -f -c "#{pane_current_path}" \; \
       split-window -h -f -c "#{pane_current_path}" \; \
       select-layout even-horizontal

##### Toggle zoom
bind z resize-pane -Z
